import "./TermOfUse.css";

const TermOfUse = () => {
  const handleBack = () => {
    window.location.href = "/dashboard";
  };

  return (
    <div className="terms-container">
      <h1 className="terms-title">Terms of Use</h1>
      <p className="terms-date">Last Updated: December 2025</p>

      <section>
        <h2>1. Introduction</h2>
        <p>
          Welcome to <strong>BudgetBee</strong> — a personal finance tracker designed to help you manage your
          income, expenses, and savings more efficiently. These Terms of Use (“Terms”) govern your access
          to and use of BudgetBee's website, application, and related services (collectively, the “Service”).
          By creating an account or using BudgetBee, you agree to be bound by these Terms and our Privacy Policy.
          If you do not agree, please do not use our Service.
        </p>
      </section>

      <section>
        <h2>2. Eligibility and Account</h2>
        <p>
          To use BudgetBee, you must be at least 16 years old or have parental consent. You are responsible
          for maintaining the confidentiality of your account credentials and for all activity that occurs
          under your account. BudgetBee is intended for <strong>personal use only</strong>; commercial or
          automated data entry is not permitted.
        </p>
      </section>

      <section>
        <h2>3. User Responsibilities</h2>
        <p>
          You agree to use BudgetBee solely for lawful purposes and in accordance with these Terms.
          You must not:
        </p>
        <ul>
          <li>Enter or share false, misleading, or fraudulent data;</li>
          <li>Attempt to access another user's data without permission;</li>
          <li>Interfere with or disrupt the Service or its security features;</li>
          <li>Use BudgetBee to promote or engage in illegal activity.</li>
        </ul>
        <p>
          You are solely responsible for the accuracy of the data you enter (e.g., income, expenses, or budget goals).
          BudgetBee provides financial tracking tools but does not offer professional financial, tax, or investment advice.
        </p>
      </section>

      <section>
        <h2>4. Data and Privacy</h2>
        <p>
          We value your privacy and are committed to protecting your personal information.
          All financial data you manually input is stored securely and used only to provide you with
          insights, charts, and summaries within your account.
        </p>
        <p>
          We do not share, sell, or publish your personal financial information to third parties without your consent,
          except as required by law. Please read our <strong>Privacy Policy</strong> for more details on how we
          collect, store, and protect your data.
        </p>
      </section>

      <section>
        <h2>5. Accuracy and Disclaimer</h2>
        <p>
          BudgetBee is designed to assist you in tracking and analyzing your personal finances.
          However, the accuracy of your reports and insights depends on the data you provide.
          We do not guarantee that any calculations, predictions, or summaries generated by the Service
          will be completely error-free or suitable for official financial purposes.
        </p>
        <p>
          You acknowledge that BudgetBee is a self-help tool and <strong>not a substitute</strong> for
          professional financial advice.
        </p>
      </section>

      <section>
        <h2>6. Security</h2>
        <p>
          We take reasonable measures to secure your account and data; however, no system is completely
          free from risk. You are responsible for maintaining the security of your device and password.
          BudgetBee will never ask for your password or financial credentials via email.
        </p>
      </section>

      <section>
        <h2>7. Modifications to the Service</h2>
        <p>
          We may modify, suspend, or discontinue certain features of BudgetBee at any time without prior notice.
          Updates to these Terms will be reflected by the “Last Updated” date at the top of this page.
          Your continued use of the Service after such updates constitutes your acceptance of the revised Terms.
        </p>
      </section>

      <section>
        <h2>8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, BudgetBee and its developers shall not be liable for any
          direct, indirect, incidental, or consequential damages resulting from your use of the Service —
          including but not limited to loss of data, profits, or financial accuracy.
        </p>
      </section>

      <section>
        <h2>9. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to BudgetBee at our discretion,
          especially in cases of misuse, security concerns, or violation of these Terms.
          Upon termination, your account data may be deleted in accordance with our data retention policy.
        </p>
      </section>

      <section>
        <h2>10. Contact</h2>
        <p>
          For questions or concerns regarding these Terms or the BudgetBee Service, contact our support team at{" "}
          <a href="mailto:support@budgetbee.com">support@budgetbee.com</a>.
        </p>
      </section>

     <div className="terms-actions">
        <button className="term-of-use-back-btn" onClick={handleBack}>
          ← Back to Dashboard
        </button>
      </div>
    </div>
  );
};

export default TermOfUse;